SCR_AvailableActionsDisplay {
 m_aActions {
  SCR_AvailableActionContext "{6A5C69DD11000001}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{6A5C69DD11000002}" {
     m_sContext "VONMenuContext"
    }
   }
   m_sTag "LC_RADIO_EAR"
   m_sAction "LC_RadioEarCycle"
   m_sName "Ear"
  }
  SCR_AvailableActionContext "{6A5C69DD11000003}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{6A5C69DD11000004}" {
     m_sContext "VONMenuContext"
    }
   }
   m_sTag "LC_RADIO_BEEPS"
   m_sAction "LC_RadioBeepCycle"
   m_sName "Beeps"
  }
  SCR_AvailableActionContext "{6A5C69DD11000005}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{6A5C69DD11000006}" {
     m_sContext "VONMenuContext"
    }
   }
   m_sTag "LC_RADIO_VOLUME"
   m_sAction "LC_RadioVolumeCycle"
   m_sName "Channel volume"
  }
  SCR_AvailableActionContext "{6A5C69DD11000007}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{6A5C69DD11000008}" {
     m_sContext "VONMenuContext"
    }
   }
   m_sTag "LC_BEEP_VOLUME"
   m_sAction "LC_BeepVolumeCycle"
   m_sName "Beep volume"
  }
  SCR_AvailableActionContext "{6A5C69DD11000009}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{6A5C69DD1100000A}" {
     m_sContext "VONMenuContext"
    }
   }
   m_sTag "LC_RADIO_KEY"
   m_sAction "LC_RadioKeyAssign"
   m_sName "Transmit key"
  }
  SCR_AvailableActionContext "{6A5C69DD1100000B}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{6A5C69DD1100000C}" {
     m_sContext "VONMenuContext"
    }
   }
   m_sTag "LC_RADIO_FREQUENCY"
   m_sAction "LC_RadioFrequencyInput"
   m_sName "Type frequency"
  }
  SCR_AvailableActionContext "{6A5C69DD1100000D}" {
   m_iTimeForHide 15000
   m_aConditions {
    SCR_IsContextEnabledCondition "{6A5C69DD1100000E}" {
     m_sContext "IngameContext"
    }
   }
   m_sTag "LC_VOICE_LEVEL"
   m_sAction "LC_VoiceLevelCycle"
   m_sName "Voice level"
  }
 }
}
