SCR_MissionHeader {
 World "{F5E250CFD54DEC2E}worlds/testWorld.ent"
 m_sName "WorkbenchTestWorld"
 m_sAuthor "Duke"
 m_sDescription "Test world for Enfusion Workbench"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}