ActionManager {
 Contexts {
  ActionContext VONContext {
   Actions {
    Action LC_VoiceLevelCycle {
     InputSource InputSourceSum "{6A5C69DD10000001}" {
      Sources {
       InputSourceCombo "{6A5C69DD10000002}" {
        FilterPreset "click"
        Sources {
         InputSourceValue "{6A5C69DD10000003}" {
          Input "keyboard:KC_LCONTROL"
         }
         InputSourceValue "{6A5C69DD10000004}" {
          Input "keyboard:KC_TAB"
          Filter InputFilterDown "{6A5C69DD10000005}" {
          }
         }
        }
       }
      }
     }
    }
    Action LC_RadioPTT1 {
     InputSource InputSourceSum "{6A5C69DD10000021}" {
     }
    }
    Action LC_RadioPTT2 {
     InputSource InputSourceSum "{6A5C69DD10000022}" {
     }
    }
    Action LC_RadioPTT3 {
     InputSource InputSourceSum "{6A5C69DD10000023}" {
     }
    }
    Action LC_RadioPTT4 {
     InputSource InputSourceSum "{6A5C69DD10000024}" {
     }
    }
   }
  }
  ActionContext VONMenuContext {
   Actions {
    Action LC_RadioVolume {
     Type AnalogRelative
     InputSource InputSourceSum "{6A5C69DD10000033}" {
      Sources {
       InputSourceCombo "{6A5C69DD10000034}" {
        Sources {
         InputSourceValue "{6A5C69DD10000035}" {
          Input "keyboard:KC_LCONTROL"
          Filter InputFilterPressed "{6A5C69DD10000036}" {
          }
         }
         InputSourceValue "{6A5C69DD10000037}" {
          Input "mouse:wheel"
          Filter InputFilterValue "{6A5C69DD10000038}" {
          }
         }
        }
       }
      }
     }
    }
    Action LC_RadioKeyAssign {
     InputSource InputSourceSum "{6A5C69DD10000027}" {
      Sources {
       InputSourceValue "{6A5C69DD10000040}" {
        FilterPreset "click"
        Input "keyboard:KC_J"
        Filter InputFilterClick "{6A5C69DD10000041}" {
        }
       }
      }
     }
    }
    Action LC_RadioFrequencyInput {
     InputSource InputSourceSum "{6A5C69DD1000002A}" {
      Sources {
       InputSourceValue "{6A5C69DD10000042}" {
        FilterPreset "click"
        Input "keyboard:KC_F"
        Filter InputFilterClick "{6A5C69DD10000043}" {
        }
       }
      }
     }
    }
    Action LC_RadioEarCycle {
     InputSource InputSourceSum "{6A5C69DD10000025}" {
      Sources {
       InputSourceValue "{6A5C69DD10000044}" {
        FilterPreset "click"
        Input "keyboard:KC_T"
        Filter InputFilterClick "{6A5C69DD10000045}" {
        }
       }
      }
     }
    }
    Action LC_RadioBeepCycle {
     InputSource InputSourceSum "{6A5C69DD10000026}" {
      Sources {
       InputSourceValue "{6A5C69DD10000046}" {
        FilterPreset "click"
        Input "keyboard:KC_K"
        Filter InputFilterClick "{6A5C69DD10000047}" {
        }
       }
      }
     }
    }
    Action LC_RadioVolumeCycle {
     InputSource InputSourceSum "{6A5C69DD10000048}" {
      Sources {
       InputSourceValue "{6A5C69DD10000049}" {
        FilterPreset "click"
        Input "keyboard:KC_L"
        Filter InputFilterClick "{6A5C69DD1000004A}" {
        }
       }
      }
     }
    }
   }
  }
 }
}
