SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{6A5C69DD10000010}" {
   m_sName "LimaCharlie"
   m_sDisplayName "Lima Charlie"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{6A5C69DD10000011}" {
     m_sActionName "LC_VoiceLevelCycle"
     m_sDisplayName "Cycle Voice Level"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5C69DD10000012}" {
     m_sActionName "LC_RadioPTT1"
     m_sDisplayName "Radio Transmit Key 1"
     m_sPreset "hold"
    }
    SCR_KeyBindingEntry "{6A5C69DD10000013}" {
     m_sActionName "LC_RadioPTT2"
     m_sDisplayName "Radio Transmit Key 2"
     m_sPreset "hold"
    }
    SCR_KeyBindingEntry "{6A5C69DD10000014}" {
     m_sActionName "LC_RadioPTT3"
     m_sDisplayName "Radio Transmit Key 3"
     m_sPreset "hold"
    }
    SCR_KeyBindingEntry "{6A5C69DD10000015}" {
     m_sActionName "LC_RadioPTT4"
     m_sDisplayName "Radio Transmit Key 4"
     m_sPreset "hold"
    }
    SCR_KeyBindingEntry "{6A5C69DD10000018}" {
     m_sActionName "LC_RadioKeyAssign"
     m_sDisplayName "Radio Menu: Move Channel to Next Transmit Key"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5C69DD1000001B}" {
     m_sActionName "LC_RadioFrequencyInput"
     m_sDisplayName "Radio Menu: Type Frequency"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5C69DD10000016}" {
     m_sActionName "LC_RadioEarCycle"
     m_sDisplayName "Radio Menu: Cycle Ear (Both / Left / Right)"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5C69DD10000017}" {
     m_sActionName "LC_RadioBeepCycle"
     m_sDisplayName "Radio Menu: Cycle Beeps"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5C69DD1000001C}" {
     m_sActionName "LC_RadioVolumeCycle"
     m_sDisplayName "Radio Menu: Cycle Channel Volume Down"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6A5C69DD1000001D}" {
     m_sActionName "LC_BeepVolumeCycle"
     m_sDisplayName "Radio Menu: Cycle Beep Volume Down (All Channels)"
     m_sPreset "click"
    }
   }
  }
 }
}
