#pragma once

/* Maps TeamSpeak clients to Reforger players. Every plugin in the channel announces
   "LC1|HELLO|<session token>|<player id>|<voice range m>|<plugin version>|<mod version>" through TeamSpeak
   plugin commands. Trailing fields are optional, so a peer that omits them is still understood. The session token
   is generated by the game server, so players from different Reforger servers sharing a channel never mix. */

#include "lc_ts.h"

#include <stddef.h>

#define LC_PEER_COMMAND_PREFIX "LC1|"

typedef struct {
    anyID client;
    int   playerId;
    float voiceRange;
    char  pluginVersion[32];
    char  modVersion[32];
} lc_peer_info;

void lc_peers_init(void);
void lc_peers_shutdown(void);
void lc_peers_reset(void);

/* Returns 1 if command was a valid HELLO. *isNewPeer is set when the sender, its session or its player id
   was not known, which is the cue to answer with our own HELLO. Voice range changes do not set it. */
int lc_peers_handle_command(anyID sender, const char* command, int* isNewPeer);

/* Reforger player id of a client in the given session, or -1. */
int lc_peers_player_id(anyID client, const char* token);

/* Copies up to max peers of the given session into out; returns how many. */
int lc_peers_list(const char* token, lc_peer_info* out, int max);

int lc_peers_count(const char* token);

/* Fills out with what this client last announced about itself, whatever session it is in.
   Returns 1 if that client has ever sent us a HELLO. */
int lc_peers_find(anyID client, lc_peer_info* out);
void lc_peers_remove(anyID client);
void lc_peers_expire(unsigned long long nowMs, unsigned long long maxAgeMs);

size_t lc_peers_format_hello(char* out, size_t cap, const char* token, int playerId, float voiceRange,
                             const char* pluginVersion, const char* modVersion);
